select PSA_SIREN,PSA_SALARIE,CC_LIBELLE,LQUAL, CASE WHEN CC_LIBELLE=LQUAL THEN 'ok' ELSE 'Ko' END AS CONTROLE FROM HR_SPRINT_SALARIES
LEFT JOIN HR_SPRINT_CHOIXCOD ON CC_CODE=PSA_LIBELLEEMPLOI AND CC_TYPE='PLE'
LEFT JOIN VENTILATION_INDIVIDUS ON  PSA_SALARIE=IND_MATRICULEHRS
LEFT JOIN VALIDCONTRAT ON IND_MATRICULEHRU=MATRI
