USE REPRISE_HRU

Go

ALTER TABLE INDIVIDU
ADD INDIVIDU_LIGNE INT IDENTITY(1, 1)

GO

ALTER TABLE EMPLOYEUR
ADD Raison_sociale varchar(255);
GO

UPDATE EMPLOYEUR SET Raison_sociale=[Raison Sociale]

Go

ALTER TABLE EMPLOYEUR
ADD SOCIETE_LIGNE INT IDENTITY(1, 1)

GO

ALTER TABLE ETABLISSEMENT
ADD ETABLISSEMENT_LIGNE INT IDENTITY(1, 1)

GO

ALTER TABLE ETABLISSEMENT

ADD Raison_sociale varchar(255);

GO

UPDATE ETABLISSEMENT SET Raison_sociale=[Raison Sociale]

Go

ALTER TABLE VALIDCONTRAT

ADD VALIDCONTRAT_LIGNE INT IDENTITY(1, 1)

GO

ALTER TABLE EMAIL
ADD EMAIL_LIGNE INT IDENTITY(1, 1)
GO

ALTER TABLE GENCONTRAT
ADD GENCONTRAT_LIGNE INT IDENTITY(1, 1);
GO

ALTER TABLE ENTETEPAIE
ADD ENTETEPAIE_LIGNE INT IDENTITY(1, 1),TRANSCO_PPAIE datetime, TRANSCO_PPAIE_FIN datetime,TRANSCO_PPAIE_TEMPORAIRE varchar(35),TRANSCO_MOIS char(2);
GO

ALTER TABLE TAUXPAS

ADD TAUXPAS_LIGNE INT IDENTITY (1,1);

GO

ALTER TABLE ENFANTS
ADD ENFANTS_LIGNE INT IDENTITY (1,1);

GO

ALTER TABLE EVENEMENTS
ADD EVENEMENTS_LIGNE INT IDENTITY (1,1);
GO

ALTER TABLE IMPUTATIONANALYTIQUE
ADD IMPUTATIONANALYTIQUE_LIGNE INT IDENTITY (1,1);
GO

ALTER TABLE CCNEMPLOYEUR
ADD CCN_EMPLOYEUR_LIGNE INT IDENTITY (1,1);
GO

ALTER TABLE TRSCLASSIFICATION1
ADD TRSCLASSIFICATION1_LIGNE INT IDENTITY (1,1);
GO

ALTER TABLE TRSCLASSIFICATION3
ADD TRSCLASSIFICATION3_LIGNE INT IDENTITY (1,1);
GO

ALTER TABLE TRSCLASSIFICATION4
ADD TRSCLASSIFICATION4_LIGNE INT IDENTITY (1,1);
GO

ALTER TABLE TRSCLASSIFICATION5
ADD TRSCLASSIFICATION5_LIGNE INT IDENTITY (1,1);
GO