SET COLONNE1='='
SET COLONNE2='1'
SET SIREN=407512185
sqlcmd -S ''- U '' -P '' -i .\script\Ajout_Nom_des_tables.sql
sqlcmd -S '' -U '' -P '' -i .\script\Export.sql -s "|" -W -h -1
echo $^|^0^|^données salariés^|^ >>.\fichiers_hrs\SALARIES_EN_TETE.asc
echo =^|^0^|^données salariés^|^ >>.\fichiers_hrs\SALARIES_EN_TETE.asc
echo $^|^1^|^SALARIES^|^PSA_SALARIE^|^PSA_NUMEROSS^|^PSA_LIBELLE^|^PSA_NOMJF^|^PSA_PRENOM^|^PSA_ETABLISSEMENT^|^PSA_ADRESSE1^|^PSA_CODEPOSTAL^|^PSA_VILLE^|^PSA_PAYS^|^PSA_DATENAISSANCE^|^PSA_COMMUNENAISS^|^PSA_DEPTNAISSANCE^|^PSA_PAYSNAISSANCE^|^PSA_NATIONALITE^|^PSA_SEXE^|^PSA_SITUATIONFAMIL^|^PSA_DATEENTREE^|^PSA_DATEANCIENNETE^|^PSA_DATESORTIE^|^PSA_CARTESEJOUR^|^PSA_DATEEXPIRSEJOUR^|^PSA_DELIVRPAR^|^PSA_PERSACHARGE^|^PSA_MODEREGLE^|^PSA_AUXILIAIRE^|^PSA_TELEPHONE^|^PSA_PORTABLE^|^PSA_COEFFICIENT^|^PSA_QUALIFICATION^|^PSA_CONDEEMPLOI^|^PSA_LIBELLEEMPLOI^|^PSA_CODEEMPLOI^|^PSA_CONVENTION^|^PSA_HORAIREMOIS^|^PSA_CIVILITE^|^PSA_CONGESPAYES^|^PSA_SALAIREMOIS1^|^PSA_SALAIREMOIS2^|^PSA_SALAIREMOIS3^|^PSA_SALAIREMOIS4^|^PSA_SALAIREMOIS5^|^PSA_TRAVAILN1^|^PSA_TRAVAILN2^|^PSA_TRAVAILN3^|^PSA_TRAVAILN4^|^PSA_CODESTAT^|^PSA_MOTIFENTREE^|^PSA_INDICE^|^PSA_NIVEAU^|^PSA_PRISEFFECTIF^|^PSA_UNITEPRISEFF^|^PSA_REGIMESS^|^PSA_DATELIBRE1^|^PSA_DATELIBRE2^|^PSA_DATELIBRE3^|^PSA_DATELIBRE4^|^PSA_BOOLLIBRE1^|^PSA_BOOLLIBRE2^|^PSA_BOOLLIBRE3^|^PSA_BOOLLIBRE4^|^PSA_LIBREPCMB1^|^PSA_LIBREPCMB2^|^PSA_LIBREPCMB3^|^PSA_LIBREPCMB4^|^PSA_ORDREAT^|^PSA_CONDEMPLOI^|^PSA_DADSPROF^|^PSA_DADSCAT^|^PSA_TAUXPARTIEL^|^PSA_REGIMEMAL^|^PSA_REGIMEVIP^|^PSA_REGIMEAT^|^PSA_TYPDSNFRAC^|^PSA_DSNFRACTION^|^PSA_TYPENATTAUXPAS^|^PSA_NATURETAUXPAS^|^PSA_UNITETRAVAIL^|^PSA_MOTIFSORTIE^|^PSA_HORHEBDO^|^PSA_ETATBULLETIN >>.\fichiers_hrs\SALARIES_EN_TETE.asc
COPY .\fichiers_hrs\SALARIES_EN_TETE.asc + .\fichiers_hrs\SALARIES.asc .\fichiers_hrs\%SIREN%_SALARIES.asc
DEL .\fichiers_hrs\SALARIES_EN_TETE.asc /f /q
DEL .\fichiers_hrs\SALARIES.asc /f /q
echo $^|^0^|^Les Données de CONTRATTRAVAIL ^|^ >>.\fichiers_hrs\CONTRATTRAVAIL_EN_TETE.asc
echo =^|^0^|^Les Données de CONTRATTRAVAIL^|^ >>.\fichiers_hrs\CONTRATTRAVAIL_EN_TETE.asc
echo $^|^1^|^CONTRATTRAVAIL^|^PCI_SALARIE^|^PCI_ORDRE^|^PCI_TYPECONTRAT^|^PCI_DEBUTCONTRAT^|^PCI_FINCONTRAT^|^PCI_ETABLISSEMENT^|^PCI_ETABLIEUTRAV^|^PCI_DNASITUATADM^|^PCI_PERPAIEMENTSAL^|^PCI_INTITULCONTRAT^|^PCI_TYPECDD^|^PCI_REGIMELOCALDSN^|^PCI_QUOTITE^|^PCI_TYPEINSEE^|^PCI_CODEINSEE^|^PCI_ANCIENNUM^|^PCI_PASEXCLU^|^PCI_DNACODUNITEHOR^|^PCI_SALARIEREMPL^|^PCI_LIBELLEEMPLOI^|^PCI_MOTIFCTINT^|^PCI_MOTIFSORTIE^|^PCI_SIRETANCIEN >>.\fichiers_hrs\CONTRATTRAVAIL_EN_TETE.asc
COPY .\fichiers_hrs\CONTRATTRAVAIL_EN_TETE.asc + .\fichiers_hrs\CONTRATTRAVAIL.asc .\fichiers_hrs\%SIREN%_CONTRATTRAVAIL.asc
DEL .\fichiers_hrs\CONTRATTRAVAIL_EN_TETE.asc /f /q
DEL .\fichiers_hrs\CONTRATTRAVAIL.asc /f /q
echo $^|^0^|^Les Données de RIB ^|^ >>.\fichiers_hrs\RIB_EN_TETE.asc
echo =^|^0^|^Les Données de RIB^|^ >>.\fichiers_hrs\RIB_EN_TETE.asc
echo $^|^1^|^RIB^|^R_AUXILIAIRE^|^R_NUMERORIB^|^R_PRINCIPAL^|^R_ETABBQ^|^R_GUICHET^|^R_NUMEROCOMPTE^|^R_CLERIB^|^R_CODEIBAN^|^R_CODEBIC^|^R_DOMICILIATION^|^R_SALAIRE^|^R_ACOMPTE^|^R_PAYS^|^R_DEVISE >>.\fichiers_hrs\RIB_EN_TETE.asc
COPY .\fichiers_hrs\RIB_EN_TETE.asc + .\fichiers_hrs\RIB.asc .\fichiers_hrs\%SIREN%_RIB.asc
DEL .\fichiers_hrs\RIB_EN_TETE.asc /f /q
DEL .\fichiers_hrs\RIB.asc /f /q
echo $^|^0^|^Les Données de DEPORTSAL ^|^ >>.\fichiers_hrs\DEPORTSAL_EN_TETE.asc
echo =^|^0^|^Les Données de DEPORTSAL^|^ >>.\fichiers_hrs\DEPORTSAL_EN_TETE.asc
echo $^|^1^|^DEPORTSAL^|^PSE_SALARIE^|^PSE_EMAILPROF >>.\fichiers_hrs\DEPORTSAL_EN_TETE.asc
COPY .\fichiers_hrs\DEPORTSAL_EN_TETE.asc + .\fichiers_hrs\DEPORTSAL.asc .\fichiers_hrs\%SIREN%_DEPORTSAL.asc
DEL .\fichiers_hrs\DEPORTSAL_EN_TETE.asc /f /q
DEL .\fichiers_hrs\DEPORTSAL.asc /f /q
echo $^|^0^|^Les Données de SALARIESCOMPL ^|^ >>.\fichiers_hrs\SALARIESCOMPL_EN_TETE.asc
echo =^|^0^|^Les Données de SALARIESCOMPL^|^ >>.\fichiers_hrs\SALARIESCOMPL_EN_TETE.asc
echo $^|^1^|^SALARIESCOMPL^|^PSZ_SALARIE^|^PSZ_DIGITALIDENT >>.\fichiers_hrs\SALARIESCOMPL_EN_TETE.asc
COPY .\fichiers_hrs\SALARIESCOMPL_EN_TETE.asc + .\fichiers_hrs\SALARIESCOMPL.asc .\fichiers_hrs\%SIREN%_SALARIESCOMPL.asc 
DEL .\fichiers_hrs\SALARIESCOMPL_EN_TETE.asc /f /q
DEL .\fichiers_hrs\SALARIESCOMPL.asc /f /q
echo $^|^0^|^Les Données de ENFANTSALARIE ^|^ >>.\fichiers_hrs\ENFANTSALARIE_EN_TETE.asc
echo =^|^0^|^Les Données de ENFANTSALARIE^|^ >>.\fichiers_hrs\ENFANTSALARIE_EN_TETE.asc
echo $^|^1^|^ENFANTSALARIE^|^PEF_SALARIE^|^PEF_ENFANT^|^PEF_NOM^|^PEF_PRENOM^|^PEF_DATENAISSANCE^|^PEF_ACHARGE^|^PEF_SEXE^|^PEF_TYPEPARENTAL >>.\fichiers_hrs\ENFANTSALARIE_EN_TETE.asc
COPY .\fichiers_hrs\ENFANTSALARIE_EN_TETE.asc + .\fichiers_hrs\ENFANTSALARIE.asc .\fichiers_hrs\%SIREN%_ENFANTSALARIE.asc
DEL .\fichiers_hrs\ENFANTSALARIE_EN_TETE.asc /f /q
DEL .\fichiers_hrs\ENFANTSALARIE.asc /f /q
echo $^|^0^|^Les Données de RETENUESALARIE ^|^ >>.\fichiers_hrs\RETENUESALARIE_ENTETE.asc
echo =^|^0^|^Les Données de RETENUESALARIE^|^ >>.\fichiers_hrs\RETENUESALARIE_ENTETE.asc
echo $^|^1^|^RETENUESALARIE^|^PRE_ORDRE^|^PRE_LIBELLE^|^PRE_DATEDEBUT^|^PRE_DATEFIN^|^PRE_MONTANTTOT^|^PRE_ACTIF^|^PRE_RETENUESAL^|^PRE_REMBMAX^|^PRE_MONTANTMENS^|^PRE_NBMOIS
COPY .\fichiers_hrs\RETENUESALARIE_ENTETE.asc + .\fichiers_hrs\RETENUESALARIE.asc .\fichiers_hrs\%SIREN%_RETENUESALARIE.asc
