USE REPRISE_HRU
GO

--Reprise RETENUESALARIE

DECLARE

@VAR_PRE_SIREN varchar(35),
@VAR_PRE_SALARIE varchar(10),
@VAR_PRE_ORDRE int,
@VAR_PRE_ORDRE_PRECEDENT int,
@VAR_PRE_LIBELLE varchar(35),
@VAR_PRE_DATEDEBUT datetime,
@VAR_PRE_DATEFIN datetime,
@VAR_SOLDE_SAISIE_ARRET numeric (9,2),
@VAR_PRE_MONTANTTOT varchar(255),
@VAR_PRE_ACTIF char(1),
@VAR_PRE_RETENUESAL char(3),
@VAR_PRE_REMBMAX char(1),
@VAR_PRE_MONTANTMENS varchar(255),
@VAR_PRE_NBMOIS int,
@VAR_CMATR varchar(10),
@VAR_TOTAL_SAISIEARRET int,
@VAR_SAISIEARRET_EN_COURS int,
@VAR_TOTAL_PENSION int,
@VAR_PENSION_EN_COURS int,
@VAR_CEMP varchar(35);

SELECT @VAR_TOTAL_SAISIEARRET=COUNT(*) FROM SAISIEARRET;
SELECT @VAR_TOTAL_PENSION=COUNT(*) FROM PENSIONALIMENTAIRE;

SET @VAR_SAISIEARRET_EN_COURS=1;
SET @VAR_PENSION_EN_COURS=1;
SET @VAR_PRE_DATEFIN='01/01/1900';
SET @VAR_PRE_REMBMAX='X';
SET @VAR_PRE_ACTIF='X';

--Reprise des saisies arrets
WHILE @VAR_SAISIEARRET_EN_COURS<=@VAR_TOTAL_SAISIEARRET

BEGIN

SELECT @VAR_CMATR=MATRI FROM SAISIEARRET WHERE SAISIEARRET_LIGNE=@VAR_SAISIEARRET_EN_COURS;--récupération du matricule 
SELECT @VAR_CEMP=CEMP FROM SAISIEARRET WHERE SAISIEARRET_LIGNE=@VAR_SAISIEARRET_EN_COURS; --récupération du CEMP
SELECT @VAR_PRE_SIREN=IND_SIREN FROM VENTILATION_INDIVIDUS WHERE IND_MATRICULEHRU=@VAR_CMATR AND IND_CEMP=@VAR_CEMP; --récupération du SIREN
SELECT @VAR_PRE_SALARIE=IND_MATRICULEHRS FROM VENTILATION_INDIVIDUS WHERE IND_MATRICULEHRU=@VAR_CMATR AND IND_CEMP=@VAR_CEMP; --récupération du matricule HRS
SELECT @VAR_PRE_ORDRE=COUNT(PRE_ORDRE+1) FROM HR_SPRINT_RETENUESALAIRE WHERE PRE_SALARIE=@VAR_PRE_SALARIE AND PRE_SIREN=@VAR_PRE_SIREN;
IF @VAR_PRE_ORDRE=0
SET @VAR_PRE_ORDRE=1;
SELECT @VAR_PRE_DATEDEBUT=CAST(CONCAT(PENOT,'01') AS datetime) FROM SAISIEARRET WHERE SAISIEARRET_LIGNE=@VAR_SAISIEARRET_EN_COURS; --récupération de la date de début de la saisie
SELECT @VAR_SOLDE_SAISIE_ARRET=SUM(MTADD-MTSUB) FROM SAISIEARRET WHERE SAISIEARRET_LIGNE=@VAR_SAISIEARRET_EN_COURS;--récupération du solde de la saisie arret
SET @VAR_PRE_MONTANTTOT=CAST(@VAR_SOLDE_SAISIE_ARRET AS varchar(255));
SELECT @VAR_PRE_LIBELLE=REFER FROM SAISIEARRET WHERE SAISIEARRET_LIGNE=@VAR_SAISIEARRET_EN_COURS;
SET @VAR_PRE_RETENUESAL='001';
SET @VAR_PRE_MONTANTMENS='';
SET @VAR_PRE_NBMOIS='';

PRINT 'Traitement du salarié '+@VAR_PRE_SALARIE+' ligne en cours '+CAST(@VAR_SAISIEARRET_EN_COURS AS varchar(255))+'/'+CAST(@VAR_TOTAL_SAISIEARRET AS varchar(255))

INSERT INTO HR_SPRINT_RETENUESALAIRE
VALUES (@VAR_PRE_SIREN,@VAR_PRE_SALARIE,@VAR_PRE_ORDRE,@VAR_PRE_LIBELLE,@VAR_PRE_DATEDEBUT,@VAR_PRE_DATEFIN,@VAR_PRE_MONTANTTOT,@VAR_PRE_ACTIF,@VAR_PRE_RETENUESAL,@VAR_PRE_REMBMAX,@VAR_PRE_MONTANTMENS,@VAR_PRE_NBMOIS);


SET @VAR_SAISIEARRET_EN_COURS=@VAR_SAISIEARRET_EN_COURS+1;
END

--Reprise des pensions alimentaires

SELECT @VAR_PRE_DATEDEBUT=PAR_VALEUR FROM PARAMETRES WHERE PAR_NOM='Date de démarrage'; --reprise au premier mois de la reprise sur Sprint sinon le logiciel vient régulariser depuis le début car il n'a pas d'historique des retenues

WHILE @VAR_PENSION_EN_COURS<=@VAR_TOTAL_PENSION

BEGIN

SELECT @VAR_CMATR=MATRI FROM PENSIONALIMENTAIRE WHERE PENSIONALIMENTAIRE_LIGNE=@VAR_PENSION_EN_COURS;--récupération du matricule 
SELECT @VAR_CEMP=CEMP FROM PENSIONALIMENTAIRE WHERE PENSIONALIMENTAIRE_LIGNE=@VAR_PENSION_EN_COURS; --récupération du CEMP
SELECT @VAR_PRE_SIREN=IND_SIREN FROM VENTILATION_INDIVIDUS WHERE IND_MATRICULEHRU=@VAR_CMATR AND IND_CEMP=@VAR_CEMP; --récupération du SIREN
SELECT @VAR_PRE_SALARIE=IND_MATRICULEHRS FROM VENTILATION_INDIVIDUS WHERE IND_MATRICULEHRU=@VAR_CMATR AND IND_CEMP=@VAR_CEMP; --récupération du matricule HRS
SELECT @VAR_PRE_ORDRE=COUNT(PRE_ORDRE+1) FROM HR_SPRINT_RETENUESALAIRE WHERE PRE_SALARIE=@VAR_PRE_SALARIE AND PRE_SIREN=@VAR_PRE_SIREN;
IF @VAR_PRE_ORDRE =0
SET @VAR_PRE_ORDRE=1;
SELECT @VAR_PRE_DATEFIN=CAST(CONCAT(PEFIN,'01') AS datetime)FROM PENSIONALIMENTAIRE WHERE PENSIONALIMENTAIRE_LIGNE=@VAR_PENSION_EN_COURS AND PEFIN<>''; --récupération date de fin de la pension
SELECT @VAR_PRE_MONTANTMENS=MTPEN FROM PENSIONALIMENTAIRE WHERE PENSIONALIMENTAIRE_LIGNE=@VAR_PENSION_EN_COURS;--récupération du solde de la saisie arret
SELECT @VAR_PRE_LIBELLE=REFER FROM SAISIEARRET WHERE SAISIEARRET_LIGNE=@VAR_SAISIEARRET_EN_COURS;
SET @VAR_PRE_RETENUESAL='002';
SET @VAR_PRE_REMBMAX='-';
SET @VAR_PRE_MONTANTTOT=0;


PRINT 'Traitement du salarié '+@VAR_PRE_SALARIE+' ligne en cours '+CAST(@VAR_PENSION_EN_COURS AS varchar(255))+'/'+CAST(@VAR_TOTAL_PENSION AS varchar(255))

INSERT INTO HR_SPRINT_RETENUESALAIRE
VALUES (@VAR_PRE_SIREN,@VAR_PRE_SALARIE,@VAR_PRE_ORDRE,@VAR_PRE_LIBELLE,@VAR_PRE_DATEDEBUT,@VAR_PRE_DATEFIN,@VAR_PRE_MONTANTTOT,@VAR_PRE_ACTIF,@VAR_PRE_RETENUESAL,@VAR_PRE_REMBMAX,@VAR_PRE_MONTANTMENS,@VAR_PRE_NBMOIS);


SET @VAR_PENSION_EN_COURS=@VAR_PENSION_EN_COURS+1;
END

GO

Print 'Fin reprise retenue salaries'