DECLARE 

@VAR_STA_SIREN varchar(17),
@VAR_STA_TABLE varchar(35),
@VAR_STA_NBRE_LIGNES int;

SET @VAR_STA_TABLE='SALARIES';

DECLARE STAT_SALARIES_CURSOR CURSOR FOR

SELECT PSA_SIREN,COUNT(PSA_SIREN) FROM HR_SPRINT_SALARIES
GROUP BY PSA_SIREN;

OPEN STAT_SALARIES_CURSOR
FETCH NEXT FROM STAT_SALARIES_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_SALARIES_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_SALARIES_CURSOR;  
DEALLOCATE STAT_SALARIES_CURSOR; 

SET @VAR_STA_TABLE='SALARIES_COMPL';

DECLARE STAT_SALARIES_COMPL_CURSOR CURSOR FOR

SELECT PSZ_SIREN,COUNT(PSZ_SIREN) FROM HR_SPRINT_SALARIECOMPL
GROUP BY PSZ_SIREN;

OPEN STAT_SALARIES_COMPL_CURSOR
FETCH NEXT FROM STAT_SALARIES_COMPL_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_SALARIES_COMPL_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_SALARIES_COMPL_CURSOR;  
DEALLOCATE STAT_SALARIES_COMPL_CURSOR; 

SET @VAR_STA_TABLE='DEPORTSAL';

DECLARE STAT_DEPORTSAL_CURSOR CURSOR FOR

SELECT PSE_SIREN,COUNT(PSE_SIREN) FROM HR_SPRINT_DEPORTSAL
GROUP BY PSE_SIREN;

OPEN STAT_DEPORTSAL_CURSOR
FETCH NEXT FROM STAT_DEPORTSAL_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_DEPORTSAL_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_DEPORTSAL_CURSOR;  
DEALLOCATE STAT_DEPORTSAL_CURSOR; 

SET @VAR_STA_TABLE='CONTRATTRAVAIL';

DECLARE STAT_CONTRATTRAVAIL_CURSOR CURSOR FOR

SELECT PCI_SIREN,COUNT(PCI_SIREN) FROM HR_SPRINT_CONTRATTRAVAIL
GROUP BY PCI_SIREN;

OPEN STAT_CONTRATTRAVAIL_CURSOR
FETCH NEXT FROM STAT_CONTRATTRAVAIL_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_CONTRATTRAVAIL_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_CONTRATTRAVAIL_CURSOR;  
DEALLOCATE STAT_CONTRATTRAVAIL_CURSOR; 

SET @VAR_STA_TABLE='RIB';

DECLARE STAT_RIB_CURSOR CURSOR FOR

SELECT R_SIREN,COUNT(R_SIREN) FROM HR_SPRINT_RIB
GROUP BY R_SIREN;

OPEN STAT_RIB_CURSOR
FETCH NEXT FROM STAT_RIB_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_RIB_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_RIB_CURSOR;  
DEALLOCATE STAT_RIB_CURSOR; 

SET @VAR_STA_TABLE='PAIEENCOURS';

DECLARE STAT_PAIEENCOURS_CURSOR CURSOR FOR

SELECT PPU_SIREN,COUNT(PPU_SIREN) FROM HR_SPRINT_PAIEENCOURS
GROUP BY PPU_SIREN;

OPEN STAT_PAIEENCOURS_CURSOR
FETCH NEXT FROM STAT_PAIEENCOURS_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_PAIEENCOURS_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_PAIEENCOURS_CURSOR;  
DEALLOCATE STAT_PAIEENCOURS_CURSOR;

SET @VAR_STA_TABLE='HISTOCUMSAL';

DECLARE STAT_HISTOCUMSAL_CURSOR CURSOR FOR

SELECT PHC_SIREN,COUNT(PHC_SIREN) FROM HR_SPRINT_HISTOCUMSAL
GROUP BY PHC_SIREN;

OPEN STAT_HISTOCUMSAL_CURSOR
FETCH NEXT FROM STAT_HISTOCUMSAL_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_HISTOCUMSAL_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_HISTOCUMSAL_CURSOR;  
DEALLOCATE STAT_HISTOCUMSAL_CURSOR;

SET @VAR_STA_TABLE='HISTOBULLETIN';

DECLARE STAT_HISTOBULLETIN_CURSOR CURSOR FOR

SELECT PHB_SIREN,COUNT(PHB_SIREN) FROM HR_SPRINT_HISTOBULLETIN
GROUP BY PHB_SIREN;

OPEN STAT_HISTOBULLETIN_CURSOR
FETCH NEXT FROM STAT_HISTOBULLETIN_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_HISTOBULLETIN_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_HISTOBULLETIN_CURSOR;  
DEALLOCATE STAT_HISTOBULLETIN_CURSOR;

SET @VAR_STA_TABLE='ENFANTSALARIE';

DECLARE STAT_ENFANTS_CURSOR CURSOR FOR

SELECT PEF_SIREN,COUNT(PEF_SIREN) FROM HR_SPRINT_ENFANTSALARIE
GROUP BY PEF_SIREN;

OPEN STAT_ENFANTS_CURSOR
FETCH NEXT FROM STAT_ENFANTS_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_ENFANTS_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_ENFANTS_CURSOR;  
DEALLOCATE STAT_ENFANTS_CURSOR;

SET @VAR_STA_TABLE='ABSENCES/CP';

DECLARE STAT_ABSENCECP_CURSOR CURSOR FOR

SELECT PCN_SIREN,COUNT(PCN_SIREN) FROM HR_SPRINT_ABSENCESALARIE
GROUP BY PCN_SIREN;

OPEN STAT_ABSENCECP_CURSOR
FETCH NEXT FROM STAT_ABSENCECP_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_ABSENCECP_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_ABSENCECP_CURSOR;  
DEALLOCATE STAT_ABSENCECP_CURSOR;

SET @VAR_STA_TABLE='RETENUE';

DECLARE STAT_RETENUE_CURSOR CURSOR FOR

SELECT PRE_SIREN,COUNT(PRE_SIREN) FROM HR_SPRINT_RETENUESALAIRE
GROUP BY PRE_SIREN;

OPEN STAT_RETENUE_CURSOR
FETCH NEXT FROM STAT_RETENUE_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_RETENUE_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_RETENUE_CURSOR;  
DEALLOCATE STAT_RETENUE_CURSOR;

SET @VAR_STA_TABLE='Ventilation analytique';

DECLARE STAT_VENTILATION_CURSOR CURSOR FOR

SELECT VEN_SIREN,COUNT(VEN_SIREN) FROM HR_SPRINT_REPRISEVENTILATIONANALYTIQUE
GROUP BY VEN_SIREN;

OPEN STAT_VENTILATION_CURSOR
FETCH NEXT FROM STAT_VENTILATION_CURSOR
INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;

WHILE @@FETCH_STATUS = 0  

BEGIN

	INSERT INTO STATISTIQUES
	VALUES  (@VAR_STA_SIREN,@VAR_STA_TABLE,@VAR_STA_NBRE_LIGNES);

	FETCH NEXT FROM STAT_RETENUE_CURSOR
	INTO @VAR_STA_SIREN,@VAR_STA_NBRE_LIGNES;
	
END

CLOSE STAT_VENTILATION_CURSOR;  
DEALLOCATE STAT_VENTILATION_CURSOR;


GO

