USE REPRISE_HRU
GO

--Reprise des RIB
 --Le script va faire une boucle à partir de VENTILATION_INDIVIDUS pas besoin de faire une boucle par société
 DECLARE

@VAR_R_SIREN varchar(35),
@VAR_R_AUXILIAIRE varchar(35),
@VAR_R_NUMERORIB int,
@VAR_R_PRINCIPAL char(1),
@VAR_R_ETABBQ varchar(8),
@VAR_R_GUICHET varchar(5),
@VAR_R_NUMEROCOMPTE varchar(20),
@VAR_R_CLERIB varchar(2),
@VAR_R_CODEIBAN varchar(70),
@VAR_R_CODEBIC varchar(35),
@VAR_R_DOMICILIATION varchar(24),
@VAR_R_SALAIRE char(1),
@VAR_R_ACOMPTE char(1),
@VAR_NATURECONTROLE varchar(255),
@VAR_SOCIETE_TOTAL int,
@VAR_SOCIETE_LIGNE int,
@VAR_SALARIE_TOTAL int,
@VAR_SALARIE_LIGNE int,
@VAR_CMATR varchar(35),
@VAR_R_PAYS char(3),
@VAR_R_DEVISE char(3),
@VAR_CONCAT_IBAN varchar(70),
@VAR_AN_TYPE varchar(255),
@VAR_AN_COMMENTAIRE varchar(255),
@VAR_RESULTATCONTROLE varchar(255),
@VAR_COMMENTAIRE varchar(255);

SET @VAR_R_PRINCIPAL='X';
SET @VAR_R_ACOMPTE='X';
SET @VAR_R_SALAIRE='X';
SET @VAR_R_NUMERORIB=1;

SET @VAR_NATURECONTROLE='Création des RIB';
SELECT @VAR_SALARIE_LIGNE=MIN(IND_LIGNE) FROM VENTILATION_INDIVIDUS;
SET @VAR_SOCIETE_LIGNE=1;

SELECT @VAR_SALARIE_TOTAL=MAX(IND_LIGNE) FROM VENTILATION_INDIVIDUS;

WHILE @VAR_SALARIE_LIGNE<=@VAR_SALARIE_TOTAL--boucle par salarié

BEGIN

SELECT @VAR_CMATR=IND_MATRICULEHRU FROM VENTILATION_INDIVIDUS WHERE @VAR_SALARIE_LIGNE=IND_LIGNE; --récupération du matricule HRU
SELECT @VAR_R_CODEIBAN=IBAN1 FROM INDIVIDU WHERE MATRI=@VAR_CMATR; --récupération de l'IBAN

IF @VAR_R_CODEIBAN<>'' --si le salarié a un IBAN 

	BEGIN
	
	SET @VAR_R_PAYS='FRA';
	SET @VAR_R_DEVISE='EUR';
	SELECT @VAR_R_AUXILIAIRE=IND_AUXILIAIRE FROM VENTILATION_INDIVIDUS WHERE @VAR_SALARIE_LIGNE=IND_LIGNE--récupération du code auxiliaire
	SELECT @VAR_R_SIREN=IND_SIREN FROM VENTILATION_INDIVIDUS WHERE @VAR_SALARIE_LIGNE=IND_LIGNE--SIREN du salarié
	SELECT @VAR_R_CODEIBAN=IBAN1 FROM INDIVIDU WHERE MATRI=@VAR_CMATR; --récupération de l'IBAN
	SELECT @VAR_R_CODEBIC=CBIC1 FROM INDIVIDU WHERE MATRI=@VAR_CMATR;--récupération du code BIC
	SELECT @VAR_R_ETABBQ=RIGHT(LEFT(IBAN1,9),5) FROM INDIVIDU WHERE MATRI=@VAR_CMATR;--code établissement
	SELECT @VAR_R_GUICHET=RIGHT(LEFT(IBAN1,14),5) FROM INDIVIDU WHERE MATRI=@VAR_CMATR;--code Guichet
	SELECT @VAR_R_NUMEROCOMPTE=RIGHT(LEFT(IBAN1,25),11) FROM INDIVIDU WHERE MATRI=@VAR_CMATR;---numéro de compte
	SELECT @VAR_R_CLERIB=RIGHT(IBAN1,2) FROM INDIVIDU WHERE MATRI=@VAR_CMATR--clé RIB
	SELECT @VAR_R_DOMICILIATION=LBNQ1 FROM INDIVIDU WHERE MATRI=@VAR_CMATR --récupération de la domiciliation
	
	SET @VAR_CONCAT_IBAN=CONCAT(LEFT(@VAR_R_CODEIBAN,4),@VAR_R_ETABBQ,@VAR_R_GUICHET,@VAR_R_NUMEROCOMPTE,@VAR_R_CLERIB)--reconstitution IBAN pour test

	IF @VAR_CONCAT_IBAN=@VAR_R_CODEIBAN --si le code est ok

		BEGIN

		INSERT INTO HR_SPRINT_RIB
		VALUES (@VAR_R_SIREN,@VAR_R_AUXILIAIRE,@VAR_R_NUMERORIB,@VAR_R_PRINCIPAL,@VAR_R_ETABBQ,@VAR_R_GUICHET,@VAR_R_NUMEROCOMPTE,@VAR_R_CLERIB,@VAR_R_CODEIBAN,
		@VAR_R_CODEBIC,@VAR_R_DOMICILIATION,@VAR_R_SALAIRE,@VAR_R_ACOMPTE,@VAR_R_PAYS,@VAR_R_DEVISE);

		UPDATE VENTILATION_INDIVIDUS SET IND_STATUS='Etape RIB', IND_REPRISE_HR_SPRINT_RIB='X' WHERE IND_AUXILIAIRE=@VAR_R_AUXILIAIRE AND IND_SIREN=@VAR_R_SIREN; --mise à jour du statuts


		PRINT 'Création du RIB pour l auxiliaire '+@VAR_R_AUXILIAIRE+'ligne en cours '+CAST(@VAR_SALARIE_LIGNE AS varchar(255))+'/'+CAST(@VAR_SALARIE_TOTAL AS varchar(255))
		
		UPDATE VENTILATION_INDIVIDUS SET IND_STATUS='Etape RIB' WHERE IND_AUXILIAIRE=@VAR_R_AUXILIAIRE;

		END

	ELSE --si le code est différent

		BEGIN

		PRINT 'Incohérence entre la valeur IBAN recalculé '+@VAR_CONCAT_IBAN+'<>'+@VAR_R_CODEIBAN

		SET @VAR_AN_TYPE='Incohérence longueur IBAN';
		SET @VAR_AN_COMMENTAIRE='Incohérence entre la valeur IBAN recalculé '+@VAR_CONCAT_IBAN+'<>'+@VAR_R_CODEIBAN;
	
		INSERT INTO ANOMALIES
		VALUES (@VAR_AN_TYPE,@VAR_R_AUXILIAIRE,@VAR_AN_COMMENTAIRE);

		SET @VAR_COMMENTAIRE=@VAR_AN_COMMENTAIRE;
		SET @VAR_RESULTATCONTROLE='Ko';

		INSERT INTO JOURNAL_DES_TRAITEMENTS  --Ajout du commentaire dans la table des traitements
		VALUES (@VAR_NATURECONTROLE,@VAR_RESULTATCONTROLE,@VAR_COMMENTAIRE);

		UPDATE VENTILATION_INDIVIDUS SET IND_STATUS='Etape RIB' WHERE IND_AUXILIAIRE=@VAR_R_AUXILIAIRE; --mise à jour du statut

		END
	END

	ELSE--si le salarié n'a pas d'IBAN

	PRINT 'Le salarié n a pas d IBAN passage au salarié suivant '+CAST(@VAR_SALARIE_LIGNE AS varchar(255))+'/'+CAST(@VAR_SALARIE_TOTAL AS varchar(255))
	
	SET @VAR_COMMENTAIRE='Le salarié n a pas d IBAN passage au salarié suivant '+CAST(@VAR_SALARIE_LIGNE AS varchar(255))+'/'+CAST(@VAR_SALARIE_TOTAL AS varchar(255));
	SET @VAR_RESULTATCONTROLE='Ok';

	INSERT INTO JOURNAL_DES_TRAITEMENTS  --Ajout du commentaire dans la table des traitements
	VALUES (@VAR_NATURECONTROLE,@VAR_RESULTATCONTROLE,@VAR_COMMENTAIRE);

	SET @VAR_SALARIE_LIGNE=@VAR_SALARIE_LIGNE+1; --incrémentation de la boucle
	UPDATE VENTILATION_INDIVIDUS SET IND_STATUS='Etape RIB' WHERE IND_AUXILIAIRE=@VAR_R_AUXILIAIRE; --mise à jour du statut


END

GO

Print 'Fin reprise RIB'