USE REPRISE_HRU
GO

--Reprise DEPORTSAL

DECLARE

@VAR_PSE_SIREN varchar(35),
@VAR_LIGNE_EMAIL int,
@VAR_SOCIETE_TOTAL int,
@VAR_SOCIETE_LIGNE int,
@VAR_TOTAL_EMAIL int,
@VAR_CEMP varchar(35),
@VAR_CMATR varchar(35),
@VAR_STATUT_MIGRATION varchar(35),
@VAR_PSE_EMAILPROF varchar(35),
@VAR_CEMP_SALARIE varchar(35),
@VAR_PSE_SALARIE varchar(35),
@VAR_NOM_TABLE char(8);

SET @VAR_NOM_TABLE='DEPORTSAL';
DECLARE EMAIL_cursor CURSOR FOR 
SELECT IND_SIREN,IND_MATRICULEHRS, EMAIL
FROM VENTILATION_INDIVIDUS
LEFT JOIN EMAIL ON MATRI=IND_MATRICULEHRU AND CEMP=IND_CEMP
WHERE EMAIL IS NOT NULL;

OPEN EMAIL_cursor
FETCH NEXT FROM EMAIL_cursor
INTO @VAR_PSE_SIREN,@VAR_PSE_SALARIE,@VAR_PSE_EMAILPROF

WHILE  @@FETCH_STATUS = 0

BEGIN

INSERT INTO HR_SPRINT_DEPORTSAL
VALUES (@VAR_PSE_SIREN,@VAR_PSE_SALARIE,@VAR_PSE_EMAILPROF,@VAR_NOM_TABLE);
			
UPDATE VENTILATION_INDIVIDUS SET IND_STATUS='Etape DEPORTSAL', IND_REPRISE_HR_SPRINT_DEPORTSAL='X' WHERE IND_MATRICULEHRU=@VAR_CMATR AND IND_CEMP=@VAR_CEMP; --mise à jour du statuts

FETCH NEXT FROM EMAIL_cursor
INTO @VAR_PSE_SIREN,@VAR_PSE_SALARIE,@VAR_PSE_EMAILPROF

END

CLOSE EMAIL_cursor;  
DEALLOCATE EMAIL_cursor;  
GO  



--SALARIECOMPL

DECLARE

@VAR_PSZ_SIREN varchar(35),
@VAR_PSZ_SALARIE varchar(10),
@VAR_PSZ_DIGITALIDENT varchar(50),
@VAR_IND_MATRICULEHRU varchar(10),
@VAR_INDIVIDU_LIGNE_EN_COURS int,
@VAR_TOTAL_INDIVIDUS int,
@VAR_NOM_TABLE char(13);

SET @VAR_NOM_TABLE='SALARIESCOMPL';
DECLARE PEOPLEDOC_cursor CURSOR FOR
SELECT IND_SIREN,IND_MATRICULEHRS,former_tech_id 
FROM VENTILATION_INDIVIDUS
LEFT JOIN PEOPLEDOC_SALARIES ON new_tech_id=IND_MATRICULEHRU;

OPEN PEOPLEDOC_cursor
FETCH NEXT FROM PEOPLEDOC_cursor
INTO @VAR_PSZ_SIREN,@VAR_PSZ_SALARIE,@VAR_PSZ_DIGITALIDENT;

WHILE @@FETCH_STATUS = 0

BEGIN

INSERT INTO HR_SPRINT_SALARIECOMPL
VALUES (@VAR_PSZ_SIREN,@VAR_PSZ_SALARIE,@VAR_PSZ_DIGITALIDENT,@VAR_NOM_TABLE);

FETCH NEXT FROM PEOPLEDOC_cursor
INTO @VAR_PSZ_SIREN,@VAR_PSZ_SALARIE,@VAR_PSZ_DIGITALIDENT;

END

CLOSE PEOPLEDOC_cursor;  
DEALLOCATE PEOPLEDOC_cursor;  
GO  

PRINT 'Fin reprise DEPORTSAL et SALARIESCOMPL'
