USE REPRISE_HRU
GO

--Reprise tabla CONTRATTRAVAIl

--Boucle par GENCONTRAT 

--Les contrats sont dans GENCONTRAT (tout reprendre) et les détails se trouvent dans VALIDCONTRAT
--Jointure GENCONTRAT.GCREF=VALIDCONTRAT.GCREF
--1 contrat plusieurs valeurs dans VALIDCONTRAT voir comment alimenter PGHISTODETAIL

--Pour chaque contrat faire une boucle pour trouver les dernières valeurs
DECLARE

@VAR_PCI_SIREN varchar(35),
@VAR_PCI_SALARIE varchar(10),
@VAR_PCI_ORDRE int,
@VAR_PCI_ORDRE_TEMPORAIRE int,
@VAR_PCI_TYPECONTRAT char(3),
@VAR_PCI_DEBUTCONTRAT datetime,
@VAR_PCI_FINCONTRAT datetime,
@VAR_PCI_ETABLISSEMENT char(3),
@VAR_ETABLISSEMENT_SALARIE varchar(35),
@VAR_PCI_ETABLIEUTRAV  char(3),
@VAR_PCI_DNASITUATADM char(3),
@VAR_PCI_PERPAIEMENTSAL char(3),
@VAR_PCI_INTITULCONTRAT char(3),
@VAR_PCI_TYPECDD char(3),
@VAR_PCI_REGIMELOCALDSN char(2),
@VAR_PCI_QUOTITE varchar(255),
@VAR_PCI_TYPEINSEE char(3),
@VAR_PCI_CODEINSEE char(5),
@VAR_PCI_ANCIENNUM char(35),
@VAR_PCI_PASEXCLU char(2),
@VAR_PCI_LIBELLEEMPLOI varchar(35),
@VAR_LIBELLE_EMPLOI_SALARIE varchar(35),
@VAR_PCI_MOTIFCTINT char(3),
@VAR_PCI_MOTIFSORTIE char(3),
@VAR_PCI_SIRETANCIEN varchar(17),
@VAR_CONTRAT_EN_COURS int,
@VAR_TOTAL_CONTRAT_SALARIE int,
@VAR_TOTAL_CONTRAT int,
@VAR_SOCIETE_TOTAL int,
@VAR_SOCIETE_LIGNE int,
@VAR_CEMP varchar(35),
@VAR_CMATR varchar(35),
@VAR_CMATR_HRS varchar(10),
@VAR_STATUT_MIGRATION varchar(35),
@VAR_CEMP_SALARIE varchar(35),
@VAR_GCREF varchar(35),
@VAR_PCI_DNACODUNITEHOR char(2),
@VAR_PCI_SALARIEREMPL_HRU varchar(10),
@VAR_PCI_SALARIEREMPL varchar(10),
@VAR_PAR_PLE_PARTAGE char(1);

SET @VAR_CONTRAT_EN_COURS=1;
SELECT @VAR_TOTAL_CONTRAT=MAX(GENCONTRAT_LIGNE) FROM GENCONTRAT;


SELECT @VAR_PAR_PLE_PARTAGE=PAR_VALEUR FROM PARAMETRES WHERE PAR_NOM='Partage PLE';--récupération du paramétrage si partage libellé emploi

WHILE @VAR_CONTRAT_EN_COURS<=@VAR_TOTAL_CONTRAT --boucle par contrat
	   	 
	BEGIN

	SELECT @VAR_CMATR=MATRI FROM GENCONTRAT WHERE GENCONTRAT_LIGNE=@VAR_CONTRAT_EN_COURS; --Récupération du matricule en cours HRU
	SELECT @VAR_CEMP_SALARIE=CEMP FROM GENCONTRAT WHERE GENCONTRAT_LIGNE=@VAR_CONTRAT_EN_COURS;--récupération de l'employeur du salarié
	
	SELECT
	@VAR_PCI_SIREN=IND_SIREN,--récupération du SIREN
	@VAR_PCI_SALARIE=IND_MATRICULEHRS,	--récupération du matricule HRS 
	@VAR_STATUT_MIGRATION=IND_STATUS--récupération du statut de la migration
	FROM VENTILATION_INDIVIDUS 
	WHERE IND_MATRICULEHRU=@VAR_CMATR AND IND_CEMP=@VAR_CEMP_SALARIE;

	SELECT @VAR_PCI_ORDRE_TEMPORAIRE=COUNT(*) FROM HR_SPRINT_CONTRATTRAVAIL WHERE PCI_SALARIE=@VAR_PCI_SALARIE AND PCI_SIREN=@VAR_PCI_SIREN; --recherche du nombre de contrat salarié
	SELECT @VAR_GCREF=GCREF FROM GENCONTRAT WHERE GENCONTRAT_LIGNE=@VAR_CONTRAT_EN_COURS; --récupération code contrat pour jointure avec VENTILCONTRAT
	IF @VAR_PCI_ORDRE_TEMPORAIRE=0--si le salarié n'avait pas de contrat alors numéro 1
			
		BEGIN
		
		SET @VAR_PCI_ORDRE=1;
		
		END
		ELSE--si le salarié avait déjà des contrats nombre de contrats +1
			BEGIN

			SET @VAR_PCI_ORDRE=@VAR_PCI_ORDRE_TEMPORAIRE+1;--incrémentation du compteur par salarié
			
			END
			
	SELECT @VAR_PCI_TYPECONTRAT=CTNAT FROM VALIDCONTRAT WHERE GCREF=@VAR_GCREF AND MATRI=@VAR_CMATR ORDER BY DVCTR DESC; --récupération du type contrat
		IF @VAR_PCI_TYPECONTRAT='01'
		SET @VAR_PCI_TYPECONTRAT='CDI';
		ELSE
		BEGIN
			SET @VAR_PCI_TYPECONTRAT='CCD';
			SET @VAR_PCI_TYPECDD='';
		END
	SELECT @VAR_PCI_DEBUTCONTRAT=CAST(DENTR AS datetime),@VAR_PCI_FINCONTRAT=CAST(DDEP AS datetime),@VAR_PCI_SALARIEREMPL_HRU=MATRR  FROM GENCONTRAT WHERE GENCONTRAT_LIGNE=@VAR_CONTRAT_EN_COURS; --récupération datetime d'entrée
	SELECT @VAR_PCI_SALARIEREMPL=IND_MATRICULEHRS FROM VENTILATION_INDIVIDUS WHERE IND_MATRICULEHRU=@VAR_PCI_SALARIEREMPL_HRU AND IND_CEMP=@VAR_CEMP;--récupération du matricule HRS
	SELECT TOP(1) @VAR_ETABLISSEMENT_SALARIE=CDETS FROM VALIDCONTRAT WHERE GCREF=@VAR_GCREF AND MATRI=@VAR_CMATR ORDER BY DVCTR DESC; --récupération du code établissement HRU du contrat
	SELECT @VAR_PCI_ETABLISSEMENT=TRA_VALEURHRS FROM TRANSCO WHERE TRA_TYPE='Etablissement' AND TRA_VALEURHRU=@VAR_ETABLISSEMENT_SALARIE AND TRA_SIREN=@VAR_PCI_SIREN;--récupération code établissement HRS
	SELECT @VAR_PCI_MOTIFSORTIE=CCDEP FROM GENCONTRAT WHERE MATRI=@VAR_CMATR AND CEMP=@VAR_CEMP ORDER BY DENTR DESC; --récupération du motif de sortie
	SET @VAR_PCI_ETABLIEUTRAV=@VAR_PCI_ETABLISSEMENT;--etablissement lieu de travail
	SET @VAR_PCI_DNASITUATADM='10';
	SET @VAR_PCI_PERPAIEMENTSAL='16';
	SET @VAR_PCI_INTITULCONTRAT='90';
	SET @VAR_PCI_PERPAIEMENTSAL='16';
	SET @VAR_PCI_REGIMELOCALDSN='99';
	SELECT TOP(1) @VAR_PCI_QUOTITE=QHMOI FROM VALIDCONTRAT WHERE GCREF=@VAR_GCREF AND MATRI=@VAR_CMATR ORDER BY DVCTR DESC; --récupération quotité de travail
		IF @VAR_PCI_QUOTITE IS NULL
		BEGIN
			SELECT TOP(1) @VAR_PCI_QUOTITE=NBJRF FROM VALIDCONTRAT WHERE GCREF=@VAR_GCREF AND MATRI=@VAR_CMATR ORDER BY DVCTR DESC
			SET @VAR_PCI_DNACODUNITEHOR='04';--forfait jours
			SET @VAR_PCI_QUOTITE='21,67';
		END
		ELSE 
		BEGIN
			SET @VAR_PCI_DNACODUNITEHOR='10';--heures
		END
	SET @VAR_PCI_TYPEINSEE='ETB'
	SELECT TOP(1) @VAR_PCI_CODEINSEE=[Code Insee Commune] FROM ETABLISSEMENT WHERE Etablissement=@VAR_ETABLISSEMENT_SALARIE;--récupération code Insee de l'établissement
	SELECT @VAR_PCI_ANCIENNUM=GCANC FROM GENCONTRAT WHERE GENCONTRAT_LIGNE=@VAR_CONTRAT_EN_COURS; --récupération ancien numéro
	SET @VAR_PCI_PASEXCLU='01';

	SELECT TOP(1) @VAR_LIBELLE_EMPLOI_SALARIE=LQUAL FROM VALIDCONTRAT WHERE GCREF=@VAR_GCREF AND MATRI=@VAR_CMATR ORDER BY DVCTR DESC;

		IF @VAR_PAR_PLE_PARTAGE='X'--si on partage les libellés d'emploi
			BEGIN
					SELECT @VAR_PCI_LIBELLEEMPLOI=TRA_VALEURHRS FROM TRANSCO WHERE TRA_VALEURHRU=@VAR_LIBELLE_EMPLOI_SALARIE AND TRA_TYPE='Emploi' AND TRA_SIREN='999999999';--récupération libellé emploi transco 
			END

		ELSE
			BEGIN
				SELECT @VAR_PCI_LIBELLEEMPLOI=TRA_VALEURHRS FROM TRANSCO WHERE TRA_VALEURHRU=@VAR_LIBELLE_EMPLOI_SALARIE AND TRA_TYPE='Emploi' AND TRA_SIREN=@VAR_PCI_SIREN;--récupération libellé emploi transco 
			END
		
	SET @VAR_PCI_MOTIFCTINT='';

	SELECT  @VAR_PCI_SIRETANCIEN=ET_SIRET 
	FROM HR_SPRINT_CONTRATTRAVAIL
	LEFT JOIN HR_SPRINT_ETABLISS ON @VAR_PCI_SIREN=ET_SIREN AND ET_ETABLISSEMENT=@VAR_PCI_ETABLISSEMENT;
	

	Print 'Création pour le salarié '+@VAR_CMATR+' d un contrat ligne en cours '+CAST(@VAR_CONTRAT_EN_COURS AS varchar(255))+'/'+CAST(@VAR_TOTAL_CONTRAT AS varchar(255))

	INSERT INTO HR_SPRINT_CONTRATTRAVAIL
	VALUES (@VAR_PCI_SIREN,@VAR_PCI_SALARIE,@VAR_PCI_ORDRE,@VAR_PCI_TYPECONTRAT,@VAR_PCI_DEBUTCONTRAT,@VAR_PCI_FINCONTRAT,@VAR_PCI_ETABLISSEMENT,
	@VAR_PCI_ETABLIEUTRAV,@VAR_PCI_DNASITUATADM,@VAR_PCI_PERPAIEMENTSAL,@VAR_PCI_INTITULCONTRAT,@VAR_PCI_TYPECDD,@VAR_PCI_REGIMELOCALDSN,@VAR_PCI_QUOTITE,
	@VAR_PCI_TYPEINSEE,@VAR_PCI_CODEINSEE,@VAR_PCI_ANCIENNUM,@VAR_PCI_PASEXCLU,@VAR_PCI_DNACODUNITEHOR,@VAR_PCI_SALARIEREMPL,@VAR_PCI_LIBELLEEMPLOI,@VAR_PCI_MOTIFCTINT,@VAR_PCI_MOTIFSORTIE,@VAR_PCI_SIRETANCIEN);

	UPDATE VENTILATION_INDIVIDUS SET IND_STATUS='Etape Contrat travail', IND_REPRISE_HR_SPRINT_CONTRATTRAVAIL='X' WHERE IND_MATRICULEHRU=@VAR_CMATR AND IND_CEMP=@VAR_CEMP; --mise à jour du statuts
 
 	
	SET @VAR_CONTRAT_EN_COURS=@VAR_CONTRAT_EN_COURS+1;--incrémentation du compteur pour passer au contrat suivant
END
 
 UPDATE HR_SPRINT_CONTRATTRAVAIL SET PCI_MOTIFSORTIE='' WHERE PCI_MOTIFSORTIE IS NULL;
 UPDATE HR_SPRINT_CONTRATTRAVAIL SET PCI_SALARIEREMPL='' WHERE PCI_SALARIEREMPL IS NULL;
 UPDATE HR_SPRINT_CONTRATTRAVAIL SET PCI_TYPECDD='' WHERE PCI_TYPECDD IS NULL;


 GO
PRINT 'Fin reprise des contrats de travail'